name: Go CI

on:
    push: 
        branches: [main]
    pull_request:


jobs:
    # Create job to run tests and linting
    go-ci:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout codebase
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.21.1

            - name: Run tests
              run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

            - name: Linting
              uses: golangci/golangci-lint-action@v4
              with:
                version: v1.54

